/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          50:  '#EFF6FF',
          100: '#DBEAFE',
          200: '#BFDBFE',
          300: '#93C5FD',
          400: '#60A5FA',
          500: '#3B82F6',
          600: '#2563EB',
          700: '#1D4ED8',
          800: '#1E40AF',
          900: '#1E3A8A',
          950: '#172554',
        },
        indigo: {
          500: '#6366F1',
          600: '#4F46E5',
          700: '#4338CA',
        },
        surface:           '#FFFFFF',
        background:        '#F8FAFC',
        border:            '#E2E8F0',
        'text-primary':    '#0F172A',
        'text-secondary':  '#64748B',
        'text-muted':      '#94A3B8',
        success:           '#10B981',
        warning:           '#F59E0B',
        danger:            '#EF4444',
        info:              '#06B6D4',
      },
      fontFamily: {
        sans:    ['Inter', 'system-ui', 'sans-serif'],
        display: ['Plus Jakarta Sans', 'Inter', 'system-ui', 'sans-serif'],
      },
      boxShadow: {
        card:       '0 1px 3px 0 rgba(0,0,0,0.06), 0 1px 2px 0 rgba(0,0,0,0.04)',
        'card-hover':'0 10px 25px -5px rgba(0,0,0,0.1), 0 4px 10px -5px rgba(0,0,0,0.05)',
        glass:      '0 8px 32px 0 rgba(31,38,135,0.15)',
        'glow-blue':'0 0 20px rgba(37,99,235,0.25)',
        'glow-lg':  '0 0 40px rgba(37,99,235,0.15)',
      },
      animation: {
        'fade-in':       'fadeIn 0.4s ease-out',
        'slide-up':      'slideUp 0.4s ease-out',
        'slide-in-right':'slideInRight 0.3s ease-out',
        shimmer:         'shimmer 2s linear infinite',
        'pulse-slow':    'pulse 3s cubic-bezier(0.4,0,0.6,1) infinite',
        float:           'float 6s ease-in-out infinite',
        'bounce-gentle': 'bounceGentle 2s ease-in-out infinite',
        'spin-slow':     'spin 3s linear infinite',
      },
      keyframes: {
        fadeIn:       { '0%': { opacity: '0' },                              '100%': { opacity: '1' } },
        slideUp:      { '0%': { transform: 'translateY(20px)', opacity: '0' },'100%': { transform: 'translateY(0)', opacity: '1' } },
        slideInRight: { '0%': { transform: 'translateX(20px)', opacity: '0' },'100%': { transform: 'translateX(0)', opacity: '1' } },
        shimmer:      { '0%': { backgroundPosition: '-200% 0' },              '100%': { backgroundPosition: '200% 0' } },
        bounceGentle: { '0%,100%': { transform: 'translateY(-4%)' },          '50%':  { transform: 'translateY(0)' } },
        float:        { '0%,100%': { transform: 'translateY(0)' },            '50%':  { transform: 'translateY(-20px)' } },
      },
      borderRadius: {
        xl:  '1rem',
        '2xl': '1.25rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
      },
      screens: { xs: '480px' },
    },
  },
  plugins: [],
};
