/**
 * Demo Data Generator for Opportunity Hub
 * ─────────────────────────────────────────
 * This file no longer auto-seeds on startup.
 * Demo opportunities are generated ONLY when an admin clicks
 * "Generate Demo Opportunities" from the ManageOpportunities page.
 *
 * Distribution:
 *   Jobs (12) | Internships (10) | Freelancing (5) | Hackathons (4) | Scholarships (3)
 *   Total = 34
 */

const demoOpportunities = [
  // ─── JOBS (12) ───────────────────────────────────────────────────────────
  {
    title: 'Senior Software Engineer – Full Stack',
    companyName: 'Razorpay',
    companyLogo: 'https://logo.clearbit.com/razorpay.com',
    category: 'Jobs', type: 'job',
    description: 'Join Razorpay\'s core engineering team to build scalable payment infrastructure used by millions of Indian businesses. You will design and implement full-stack features using React and Node.js, collaborate with product managers, and contribute to system design reviews. We value clean code, robust testing, and a bias for impact.',
    requiredSkills: ['React', 'Node.js', 'PostgreSQL', 'Redis', 'System Design'],
    eligibility: 'B.Tech/M.Tech in CS/IT or equivalent. 3+ years full-stack experience.',
    location: 'Bengaluru', workMode: 'Hybrid',
    salary: '₹30,00,000 – ₹45,00,000/year', salaryMin: 3000000, salaryMax: 4500000,
    applicationDeadline: new Date('2026-09-15'),
    applyLink: 'https://razorpay.com/jobs/',
    contactEmail: 'careers@razorpay.com',
    status: 'Active', isFeatured: true, isDemo: true,
  },
  {
    title: 'Product Manager – Growth',
    companyName: 'Swiggy',
    companyLogo: 'https://logo.clearbit.com/swiggy.com',
    category: 'Jobs', type: 'job',
    description: 'Drive Swiggy\'s customer acquisition and retention strategy as a Growth PM. You will own OKRs for user engagement, run A/B experiments, partner with engineering on feature rollouts, and define the north-star metrics for the growth flywheel.',
    requiredSkills: ['Product Strategy', 'A/B Testing', 'SQL', 'Analytics', 'User Research'],
    eligibility: 'MBA or equivalent with 2+ years as PM in a consumer tech company.',
    location: 'Bengaluru', workMode: 'Onsite',
    salary: '₹28,00,000 – ₹38,00,000/year', salaryMin: 2800000, salaryMax: 3800000,
    applicationDeadline: new Date('2026-09-20'),
    applyLink: 'https://careers.swiggy.com/',
    contactEmail: 'talent@swiggy.com',
    status: 'Active', isFeatured: true, isDemo: true,
  },
  {
    title: 'Machine Learning Engineer',
    companyName: 'Google India',
    companyLogo: 'https://logo.clearbit.com/google.com',
    category: 'Jobs', type: 'job',
    description: 'Work on large-scale ML systems that power Google Search, Ads, and Assistant. You will design, train, and deploy production ML models, optimize pipelines with TensorFlow and JAX, and collaborate with world-class researchers to push the boundaries of AI.',
    requiredSkills: ['Python', 'TensorFlow', 'PyTorch', 'MLOps', 'Distributed Systems'],
    eligibility: 'M.Tech/PhD in CS, Statistics, or related field. Strong ML fundamentals.',
    location: 'Hyderabad', workMode: 'Hybrid',
    salary: '₹50,00,000 – ₹80,00,000/year', salaryMin: 5000000, salaryMax: 8000000,
    applicationDeadline: new Date('2026-10-01'),
    applyLink: 'https://careers.google.com/',
    contactEmail: 'university-recruiting@google.com',
    status: 'Active', isFeatured: true, isDemo: true,
  },
  {
    title: 'Backend Developer – Microservices',
    companyName: 'Zepto',
    companyLogo: 'https://logo.clearbit.com/zeptonow.com',
    category: 'Jobs', type: 'job',
    description: 'Build the backend systems that power Zepto\'s 10-minute delivery network. You will architect microservices using Go and Kubernetes, design event-driven systems with Kafka, and ensure 99.99% uptime for order management and inventory APIs.',
    requiredSkills: ['Go', 'Kubernetes', 'Kafka', 'PostgreSQL', 'gRPC'],
    eligibility: 'B.Tech in CS/IT or equivalent. 2+ years backend experience.',
    location: 'Mumbai', workMode: 'Hybrid',
    salary: '₹18,00,000 – ₹28,00,000/year', salaryMin: 1800000, salaryMax: 2800000,
    applicationDeadline: new Date('2026-09-10'),
    applyLink: 'https://zeptonow.com/careers',
    contactEmail: 'hiring@zeptonow.com',
    status: 'Active', isFeatured: false, isDemo: true,
  },
  {
    title: 'DevOps Engineer – Cloud Infrastructure',
    companyName: 'PhonePe',
    companyLogo: 'https://logo.clearbit.com/phonepe.com',
    category: 'Jobs', type: 'job',
    description: 'Design and manage PhonePe\'s cloud infrastructure serving 500M+ users. Responsibilities include CI/CD pipeline management, infrastructure as code using Terraform, container orchestration with Kubernetes, and incident response across AWS and GCP.',
    requiredSkills: ['Kubernetes', 'Terraform', 'AWS', 'Docker', 'CI/CD', 'Python'],
    eligibility: 'B.Tech in CS/IT or equivalent. 2–4 years DevOps/SRE experience.',
    location: 'Bengaluru', workMode: 'Hybrid',
    salary: '₹20,00,000 – ₹30,00,000/year', salaryMin: 2000000, salaryMax: 3000000,
    applicationDeadline: new Date('2026-09-25'),
    applyLink: 'https://careers.phonepe.com/',
    contactEmail: 'careers@phonepe.com',
    status: 'Active', isFeatured: false, isDemo: true,
  },
  {
    title: 'Data Scientist – Risk Analytics',
    companyName: 'CRED',
    companyLogo: 'https://logo.clearbit.com/cred.club',
    category: 'Jobs', type: 'job',
    description: 'Join CRED\'s Risk & Analytics team to build credit scoring models, fraud detection systems, and member behaviour propensity models. You will work with massive transaction datasets and deploy ML models that impact lending decisions for India\'s top credit card users.',
    requiredSkills: ['Python', 'SQL', 'Scikit-learn', 'XGBoost', 'Statistics', 'Spark'],
    eligibility: 'B.Tech/M.Tech/MBA in quantitative field. 1–3 years data science experience.',
    location: 'Bengaluru', workMode: 'Hybrid',
    salary: '₹22,00,000 – ₹32,00,000/year', salaryMin: 2200000, salaryMax: 3200000,
    applicationDeadline: new Date('2026-09-18'),
    applyLink: 'https://careers.cred.club/',
    contactEmail: 'jobs@cred.club',
    status: 'Active', isFeatured: false, isDemo: true,
  },
  {
    title: 'iOS Developer – Consumer App',
    companyName: 'Myntra',
    companyLogo: 'https://logo.clearbit.com/myntra.com',
    category: 'Jobs', type: 'job',
    description: 'Build world-class fashion shopping experiences on iOS for Myntra\'s 50M+ monthly active users. You will own end-to-end feature development in Swift, work on performance optimization, AR try-on features, and collaborate closely with UX designers.',
    requiredSkills: ['Swift', 'UIKit', 'SwiftUI', 'Xcode', 'REST APIs', 'Git'],
    eligibility: 'B.Tech in CS or equivalent. 2+ years iOS development experience.',
    location: 'Bengaluru', workMode: 'Hybrid',
    salary: '₹16,00,000 – ₹24,00,000/year', salaryMin: 1600000, salaryMax: 2400000,
    applicationDeadline: new Date('2026-09-12'),
    applyLink: 'https://careers.myntra.com/',
    contactEmail: 'hr@myntra.com',
    status: 'Active', isFeatured: false, isDemo: true,
  },
  {
    title: 'Cybersecurity Analyst – SOC',
    companyName: 'Wipro CyberDefense',
    companyLogo: 'https://logo.clearbit.com/wipro.com',
    category: 'Jobs', type: 'job',
    description: 'Monitor, detect, and respond to cybersecurity threats in Wipro\'s 24×7 Security Operations Center. You will triage SIEM alerts, conduct threat hunting, perform malware analysis, and coordinate incident response with global enterprise clients.',
    requiredSkills: ['SIEM (Splunk/QRadar)', 'Networking', 'Malware Analysis', 'Linux', 'MITRE ATT&CK'],
    eligibility: 'B.Tech in CS/IT with CompTIA Security+, CEH, or equivalent certification.',
    location: 'Pune', workMode: 'Onsite',
    salary: '₹8,00,000 – ₹14,00,000/year', salaryMin: 800000, salaryMax: 1400000,
    applicationDeadline: new Date('2026-09-30'),
    applyLink: 'https://careers.wipro.com/',
    contactEmail: 'cybercareers@wipro.com',
    status: 'Active', isFeatured: false, isDemo: true,
  },
  {
    title: 'UI/UX Designer – Enterprise SaaS',
    companyName: 'Freshworks',
    companyLogo: 'https://logo.clearbit.com/freshworks.com',
    category: 'Jobs', type: 'job',
    description: 'Shape the design language for Freshdesk, Freshsales, and Freshservice used by 65,000+ businesses worldwide. Responsibilities include end-to-end product design, design system maintenance, usability testing, and cross-functional collaboration with engineering and product.',
    requiredSkills: ['Figma', 'Design Systems', 'Prototyping', 'User Research', 'Accessibility'],
    eligibility: 'B.Des/M.Des or equivalent. 2+ years of SaaS product design experience.',
    location: 'Chennai', workMode: 'Hybrid',
    salary: '₹14,00,000 – ₹20,00,000/year', salaryMin: 1400000, salaryMax: 2000000,
    applicationDeadline: new Date('2026-09-22'),
    applyLink: 'https://careers.freshworks.com/',
    contactEmail: 'design-talent@freshworks.com',
    status: 'Active', isFeatured: false, isDemo: true,
  },
  {
    title: 'Technical Writer – Developer Docs',
    companyName: 'Postman',
    companyLogo: 'https://logo.clearbit.com/postman.com',
    category: 'Jobs', type: 'job',
    description: 'Create, maintain, and improve API documentation, tutorials, and developer guides for Postman\'s 30M+ users. You will work alongside engineering teams to document new features, write code samples in multiple languages, and ensure a world-class developer experience.',
    requiredSkills: ['Technical Writing', 'API Documentation', 'Markdown', 'REST APIs', 'Git'],
    eligibility: 'Bachelor\'s in English, CS, or equivalent. 1+ years technical writing experience.',
    location: 'Remote', workMode: 'Remote',
    salary: '₹10,00,000 – ₹16,00,000/year', salaryMin: 1000000, salaryMax: 1600000,
    applicationDeadline: new Date('2026-09-28'),
    applyLink: 'https://careers.postman.com/',
    contactEmail: 'jobs@postman.com',
    status: 'Active', isFeatured: false, isDemo: true,
  },
  {
    title: 'Cloud Solutions Architect',
    companyName: 'Microsoft India',
    companyLogo: 'https://logo.clearbit.com/microsoft.com',
    category: 'Jobs', type: 'job',
    description: 'Help Microsoft enterprise customers design and migrate workloads to Azure. You will deliver architecture workshops, create proof-of-concept solutions, and guide clients through cloud-native transformations using Azure services including AKS, Azure Functions, and Cosmos DB.',
    requiredSkills: ['Azure', 'Cloud Architecture', 'Kubernetes', 'Networking', 'Solution Design'],
    eligibility: 'B.Tech/M.Tech in CS or equivalent. Azure certifications preferred. 4+ years experience.',
    location: 'Hyderabad', workMode: 'Hybrid',
    salary: '₹35,00,000 – ₹55,00,000/year', salaryMin: 3500000, salaryMax: 5500000,
    applicationDeadline: new Date('2026-10-05'),
    applyLink: 'https://careers.microsoft.com/',
    contactEmail: 'mscareers@microsoft.com',
    status: 'Active', isFeatured: true, isDemo: true,
  },
  {
    title: 'Android Developer – FinTech',
    companyName: 'Groww',
    companyLogo: 'https://logo.clearbit.com/groww.in',
    category: 'Jobs', type: 'job',
    description: 'Build Groww\'s Android app used by 10M+ investors to trade stocks, mutual funds, and derivatives. Own feature development in Kotlin, optimize app performance and startup time, implement real-time market data feeds, and contribute to the design system.',
    requiredSkills: ['Kotlin', 'Android SDK', 'Jetpack Compose', 'REST APIs', 'RxJava'],
    eligibility: 'B.Tech in CS or equivalent. 2+ years of Android development experience.',
    location: 'Bengaluru', workMode: 'Hybrid',
    salary: '₹18,00,000 – ₹28,00,000/year', salaryMin: 1800000, salaryMax: 2800000,
    applicationDeadline: new Date('2026-09-15'),
    applyLink: 'https://careers.groww.in/',
    contactEmail: 'hiring@groww.in',
    status: 'Active', isFeatured: false, isDemo: true,
  },

  // ─── INTERNSHIPS (10) ────────────────────────────────────────────────────
  {
    title: 'Software Development Intern – Summer 2026',
    companyName: 'Amazon India',
    companyLogo: 'https://logo.clearbit.com/amazon.com',
    category: 'Internships', type: 'internship',
    description: 'Join Amazon\'s SDE internship program and work on production systems impacting millions of customers. You will be assigned to a real team, mentor-guided, and ship actual features during the 3-month engagement. Full-time return offer for top performers.',
    requiredSkills: ['Java / Python / C++', 'Data Structures', 'Algorithms', 'OOP', 'Problem Solving'],
    eligibility: 'Pre-final year B.Tech/M.Tech students in CS/IT. CGPA ≥ 7.5.',
    location: 'Hyderabad', workMode: 'Onsite',
    salary: '₹1,00,000/month', salaryMin: 100000, salaryMax: 100000,
    applicationDeadline: new Date('2026-08-20'),
    applyLink: 'https://www.amazon.jobs/en/teams/internships-and-fresh-graduates',
    contactEmail: 'university@amazon.com',
    status: 'Active', isFeatured: true, isDemo: true,
  },
  {
    title: 'Frontend Engineering Intern',
    companyName: 'Meesho',
    companyLogo: 'https://logo.clearbit.com/meesho.com',
    category: 'Internships', type: 'internship',
    description: 'Work alongside Meesho\'s frontend team to build features for India\'s fastest-growing social commerce platform. You will write production React code, implement pixel-perfect UIs, optimize Core Web Vitals, and participate in daily standups and design reviews.',
    requiredSkills: ['React', 'JavaScript', 'TypeScript', 'CSS/Tailwind', 'Git'],
    eligibility: 'Pre-final year students in CS/IT. Strong React portfolio required.',
    location: 'Bengaluru', workMode: 'Hybrid',
    salary: '₹40,000/month', salaryMin: 40000, salaryMax: 40000,
    applicationDeadline: new Date('2026-08-10'),
    applyLink: 'https://careers.meesho.com/',
    contactEmail: 'intern@meesho.com',
    status: 'Active', isFeatured: false, isDemo: true,
  },
  {
    title: 'Data Science Intern – NLP',
    companyName: 'MuSigma',
    companyLogo: 'https://logo.clearbit.com/mu-sigma.com',
    category: 'Internships', type: 'internship',
    description: 'Assist the NLP research team in building text classification, sentiment analysis, and information extraction models for Fortune 500 clients. You will clean datasets, experiment with transformer models (BERT, T5), and present findings to business stakeholders.',
    requiredSkills: ['Python', 'NLP', 'HuggingFace Transformers', 'Pandas', 'Jupyter'],
    eligibility: 'Pre-final/final year students in CS, Statistics, or Data Science.',
    location: 'Bengaluru', workMode: 'Onsite',
    salary: '₹25,000/month', salaryMin: 25000, salaryMax: 25000,
    applicationDeadline: new Date('2026-08-15'),
    applyLink: 'https://www.mu-sigma.com/careers',
    contactEmail: 'campus@mu-sigma.com',
    status: 'Active', isFeatured: false, isDemo: true,
  },
  {
    title: 'Product Design Intern',
    companyName: 'Zomato',
    companyLogo: 'https://logo.clearbit.com/zomato.com',
    category: 'Internships', type: 'internship',
    description: 'Work with Zomato\'s award-winning design team to create user interfaces for the Zomato and Blinkit apps. Responsibilities include wireframing, prototyping in Figma, conducting user interviews, and presenting design rationale to the product team.',
    requiredSkills: ['Figma', 'UX Research', 'Prototyping', 'Visual Design', 'Mobile UI'],
    eligibility: 'Students in design, communication, or CS. Strong Figma portfolio required.',
    location: 'Gurugram', workMode: 'Onsite',
    salary: '₹30,000/month', salaryMin: 30000, salaryMax: 30000,
    applicationDeadline: new Date('2026-08-05'),
    applyLink: 'https://careers.zomato.com/',
    contactEmail: 'design-intern@zomato.com',
    status: 'Active', isFeatured: false, isDemo: true,
  },
  {
    title: 'Backend Engineering Intern – Go',
    companyName: 'Slice',
    companyLogo: 'https://logo.clearbit.com/sliceit.com',
    category: 'Internships', type: 'internship',
    description: 'Build APIs and microservices in Go for Slice\'s credit card and BNPL platform. You will work on payment gateway integrations, event-driven architectures, and internal tooling. Excellent learning environment with senior mentors assigned per intern.',
    requiredSkills: ['Go', 'REST APIs', 'PostgreSQL', 'Docker', 'Git'],
    eligibility: 'Pre-final year B.Tech students. Prior experience in any backend language.',
    location: 'Bengaluru', workMode: 'Hybrid',
    salary: '₹35,000/month', salaryMin: 35000, salaryMax: 35000,
    applicationDeadline: new Date('2026-08-12'),
    applyLink: 'https://careers.sliceit.com/',
    contactEmail: 'campus@sliceit.com',
    status: 'Active', isFeatured: false, isDemo: true,
  },
  {
    title: 'Marketing Analytics Intern',
    companyName: 'Nykaa',
    companyLogo: 'https://logo.clearbit.com/nykaa.com',
    category: 'Internships', type: 'internship',
    description: 'Support Nykaa\'s growth marketing team by analysing campaign performance, building dashboards in Looker Studio, running attribution models, and identifying key growth levers across social media, email, and push notification channels.',
    requiredSkills: ['SQL', 'Excel', 'Google Analytics', 'Data Visualization', 'Python (basics)'],
    eligibility: 'BBA/MBA/B.Tech students. Strong analytical mindset and attention to detail.',
    location: 'Mumbai', workMode: 'Hybrid',
    salary: '₹20,000/month', salaryMin: 20000, salaryMax: 20000,
    applicationDeadline: new Date('2026-08-18'),
    applyLink: 'https://careers.nykaa.com/',
    contactEmail: 'intern.marketing@nykaa.com',
    status: 'Active', isFeatured: false, isDemo: true,
  },
  {
    title: 'DevOps / Cloud Intern',
    companyName: 'Infosys',
    companyLogo: 'https://logo.clearbit.com/infosys.com',
    category: 'Internships', type: 'internship',
    description: 'Gain hands-on cloud and DevOps experience by working on internal automation projects and client cloud migrations. You will set up CI/CD pipelines with Jenkins/GitHub Actions, manage AWS resources, and write infrastructure code using Terraform.',
    requiredSkills: ['Linux', 'AWS Basics', 'Docker', 'Git', 'Shell Scripting'],
    eligibility: 'Pre-final/final year B.Tech students in CS/IT/ECE.',
    location: 'Mysore', workMode: 'Onsite',
    salary: '₹18,000/month', salaryMin: 18000, salaryMax: 18000,
    applicationDeadline: new Date('2026-08-25'),
    applyLink: 'https://careers.infosys.com/',
    contactEmail: 'campushiring@infosys.com',
    status: 'Active', isFeatured: false, isDemo: true,
  },
  {
    title: 'Blockchain Development Intern',
    companyName: 'Polygon Technology',
    companyLogo: 'https://logo.clearbit.com/polygon.technology',
    category: 'Internships', type: 'internship',
    description: 'Join Polygon Labs\' core developer relations team and build sample dApps, write Solidity smart contracts, contribute to open-source repositories, and create developer tutorials for the Polygon zkEVM and PoS networks.',
    requiredSkills: ['Solidity', 'JavaScript', 'Web3.js/Ethers.js', 'Hardhat', 'React'],
    eligibility: 'Any year student with demonstrated blockchain or Web3 experience.',
    location: 'Remote', workMode: 'Remote',
    salary: '$2,000/month (USD)', salaryMin: 165000, salaryMax: 165000,
    applicationDeadline: new Date('2026-08-08'),
    applyLink: 'https://polygon.technology/careers',
    contactEmail: 'devrel@polygon.technology',
    status: 'Active', isFeatured: true, isDemo: true,
  },
  {
    title: 'Content Writing Intern – Tech Blog',
    companyName: 'GeeksforGeeks',
    companyLogo: 'https://logo.clearbit.com/geeksforgeeks.org',
    category: 'Internships', type: 'internship',
    description: 'Write technical articles on data structures, algorithms, web development, and system design for an audience of 10M+ developers. You will research topics, write high-quality code examples, respond to editorial feedback, and maintain publishing deadlines.',
    requiredSkills: ['Technical Writing', 'Data Structures', 'Programming (any language)', 'Markdown'],
    eligibility: 'Any year student with strong CS fundamentals and good written English.',
    location: 'Remote', workMode: 'Remote',
    salary: '₹8,000 – ₹15,000/month (per-article basis)', salaryMin: 8000, salaryMax: 15000,
    applicationDeadline: new Date('2026-08-30'),
    applyLink: 'https://www.geeksforgeeks.org/careers/',
    contactEmail: 'contribute@geeksforgeeks.org',
    status: 'Active', isFeatured: false, isDemo: true,
  },
  {
    title: 'Research Intern – AI Safety',
    companyName: 'IIIT Hyderabad – CVIT Lab',
    companyLogo: 'https://logo.clearbit.com/iiit.ac.in',
    category: 'Internships', type: 'internship',
    description: 'Conduct research under faculty guidance on AI safety topics including interpretability, robustness, and alignment of large language models. You will review literature, run experiments with PyTorch, write research reports, and potentially co-author papers.',
    requiredSkills: ['Python', 'PyTorch', 'Deep Learning', 'Research Methodology', 'LaTeX'],
    eligibility: 'Pre-final/final year B.Tech or M.Tech students with strong ML background.',
    location: 'Hyderabad', workMode: 'Onsite',
    salary: '₹15,000/month (research stipend)', salaryMin: 15000, salaryMax: 15000,
    applicationDeadline: new Date('2026-08-01'),
    applyLink: 'https://cvit.iiit.ac.in/internships',
    contactEmail: 'cvit-internships@iiit.ac.in',
    status: 'Active', isFeatured: false, isDemo: true,
  },

  // ─── FREELANCING (5) ─────────────────────────────────────────────────────
  {
    title: 'Freelance React Developer – SaaS Dashboard',
    companyName: 'PixelForge Studio',
    companyLogo: 'https://ui-avatars.com/api/?name=PixelForge&background=6366f1&color=fff&size=200',
    category: 'Freelancing', type: 'freelancing',
    description: 'We need an experienced React developer to build an analytics dashboard for our B2B SaaS product. The project involves integration with Recharts, RESTful API consumption, user authentication, and responsive design. Clear specs provided. 4–6 weeks estimated.',
    requiredSkills: ['React', 'TypeScript', 'Tailwind CSS', 'REST APIs', 'Recharts'],
    eligibility: 'Portfolio demonstrating similar dashboard projects. Reliable communication a must.',
    location: 'Remote', workMode: 'Remote',
    salary: '₹60,000 – ₹90,000/project', salaryMin: 60000, salaryMax: 90000,
    applicationDeadline: new Date('2026-08-05'),
    applyLink: 'https://www.upwork.com/',
    contactEmail: 'dev-contracts@pixelforge.io',
    status: 'Active', isFeatured: false, isDemo: true,
  },
  {
    title: 'Freelance Mobile App Developer – Flutter',
    companyName: 'LaunchPad Ventures',
    companyLogo: 'https://ui-avatars.com/api/?name=LaunchPad&background=0ea5e9&color=fff&size=200',
    category: 'Freelancing', type: 'freelancing',
    description: 'Build a cross-platform Flutter app for a fitness startup. Features include workout tracking, Firebase auth & Firestore, push notifications, Stripe in-app purchases, and an admin panel. Figma designs ready. MVP must be delivered in 8 weeks.',
    requiredSkills: ['Flutter', 'Dart', 'Firebase', 'Stripe SDK', 'REST APIs'],
    eligibility: 'Published apps on Play Store or App Store preferred. Figma familiarity required.',
    location: 'Remote', workMode: 'Remote',
    salary: '₹1,20,000 – ₹1,80,000/project', salaryMin: 120000, salaryMax: 180000,
    applicationDeadline: new Date('2026-08-10'),
    applyLink: 'https://www.freelancer.com/',
    contactEmail: 'projects@launchpadventures.in',
    status: 'Active', isFeatured: false, isDemo: true,
  },
  {
    title: 'Freelance Graphic Designer – Brand Identity',
    companyName: 'Verdant Organics',
    companyLogo: 'https://ui-avatars.com/api/?name=Verdant&background=059669&color=fff&size=200',
    category: 'Freelancing', type: 'freelancing',
    description: 'Design a complete brand identity for a sustainable D2C organic food startup. Deliverables: logo suite, colour palette, typography guide, packaging mockups, social media templates, and a brand guidelines PDF. Creative freedom within a green, earthy aesthetic.',
    requiredSkills: ['Adobe Illustrator', 'Photoshop', 'Brand Design', 'Typography', 'Packaging Design'],
    eligibility: 'Portfolio with at least 3 brand identity projects. Eye for clean, modern design.',
    location: 'Remote', workMode: 'Remote',
    salary: '₹40,000 – ₹65,000/project', salaryMin: 40000, salaryMax: 65000,
    applicationDeadline: new Date('2026-08-15'),
    applyLink: 'https://www.fiverr.com/',
    contactEmail: 'design@verdantorganics.com',
    status: 'Active', isFeatured: false, isDemo: true,
  },
  {
    title: 'Freelance SEO Content Writer',
    companyName: 'TechPulse Media',
    companyLogo: 'https://ui-avatars.com/api/?name=TechPulse&background=d97706&color=fff&size=200',
    category: 'Freelancing', type: 'freelancing',
    description: 'Write SEO-optimised long-form articles (1500–3000 words) on tech, SaaS, and cybersecurity topics for a growing tech blog. 8–12 articles per month, keyword briefs provided, on-page SEO guidelines shared. Payment per article on submission.',
    requiredSkills: ['SEO Writing', 'Tech Content', 'Keyword Research', 'WordPress', 'Grammarly'],
    eligibility: 'Demonstrated writing portfolio in tech niche. Native or near-native English.',
    location: 'Remote', workMode: 'Remote',
    salary: '₹4,000 – ₹7,000/article', salaryMin: 4000, salaryMax: 7000,
    applicationDeadline: new Date('2026-08-20'),
    applyLink: 'https://www.linkedin.com/jobs/',
    contactEmail: 'editorial@techpulsemedia.com',
    status: 'Active', isFeatured: false, isDemo: true,
  },
  {
    title: 'Freelance WordPress Developer',
    companyName: 'Horizon Consulting',
    companyLogo: 'https://ui-avatars.com/api/?name=Horizon&background=7c3aed&color=fff&size=200',
    category: 'Freelancing', type: 'freelancing',
    description: 'Revamp our corporate WordPress website. Tasks include custom theme development with Elementor Pro, WooCommerce integration, page speed optimisation (Core Web Vitals), basic on-page SEO setup, and staff training. 3-week timeline.',
    requiredSkills: ['WordPress', 'PHP', 'Elementor Pro', 'WooCommerce', 'CSS', 'SEO Basics'],
    eligibility: 'Portfolio of at least 5 WordPress sites. Must be able to handle hosting setup independently.',
    location: 'Remote', workMode: 'Remote',
    salary: '₹30,000 – ₹50,000/project', salaryMin: 30000, salaryMax: 50000,
    applicationDeadline: new Date('2026-08-08'),
    applyLink: 'https://www.toptal.com/',
    contactEmail: 'it@horizonconsulting.in',
    status: 'Active', isFeatured: false, isDemo: true,
  },

  // ─── HACKATHONS (4) ──────────────────────────────────────────────────────
  {
    title: 'Smart India Hackathon 2026 – Software Edition',
    companyName: 'Ministry of Education, Govt. of India',
    companyLogo: 'https://logo.clearbit.com/sih.gov.in',
    category: 'Hackathons', type: 'hackathon',
    description: 'India\'s biggest hackathon invites student teams to solve 400+ problem statements from government ministries and PSUs. 36-hour hackathon at IIT/NIT campuses. Categories include agriculture, health, education, smart cities, and disaster management. ₹1 lakh prize per winning team.',
    requiredSkills: ['Any Tech Stack', 'Problem Solving', 'Teamwork', 'Presentation Skills'],
    eligibility: 'Teams of 2–6 students from any recognised college. One faculty mentor required.',
    location: 'Pan India (Multiple Venues)', workMode: 'Onsite',
    salary: '₹1,00,000 prize per winner (per problem)', salaryMin: 100000, salaryMax: 100000,
    applicationDeadline: new Date('2026-09-01'),
    applyLink: 'https://www.sih.gov.in/',
    contactEmail: 'support@sih.gov.in',
    status: 'Active', isFeatured: true, isDemo: true,
  },
  {
    title: 'HackWithInfy 2026 – Infosys National Hackathon',
    companyName: 'Infosys',
    companyLogo: 'https://logo.clearbit.com/infosys.com',
    category: 'Hackathons', type: 'hackathon',
    description: 'HackWithInfy challenges students to build innovative solutions using Infosys technologies including Cobalt Cloud, Springboard AI, and Finacle. Two rounds: online qualifier then final at Infosys campus. Top performers get PPO (Pre-Placement Offers) for full-time roles.',
    requiredSkills: ['Python / Java / JavaScript', 'Cloud Basics', 'API Development', 'Presentation'],
    eligibility: 'Final year or pre-final year students from partner colleges.',
    location: 'Mysore (Final Round)', workMode: 'Hybrid',
    salary: 'Prizes + PPO opportunities worth up to ₹20,00,000 CTC',
    applicationDeadline: new Date('2026-08-25'),
    applyLink: 'https://www.infosys.com/careers/hackwithInfy.html',
    contactEmail: 'hackwithinfy@infosys.com',
    status: 'Active', isFeatured: false, isDemo: true,
  },
  {
    title: 'GenAI Hackathon – Build with Gemini',
    companyName: 'Google Developer Groups India',
    companyLogo: 'https://logo.clearbit.com/developers.google.com',
    category: 'Hackathons', type: 'hackathon',
    description: 'A 48-hour generative AI hackathon powered by Google. Teams will build innovative products using the Gemini API, Vertex AI, and Firebase. Themes include education, accessibility, and sustainability. Google Cloud credits provided to all teams. Mentors from Google APAC.',
    requiredSkills: ['Python / JavaScript', 'Gemini API', 'Firebase', 'Prompt Engineering'],
    eligibility: 'Open to all students and recent graduates (graduated after Jan 2024).',
    location: 'Bengaluru', workMode: 'Onsite',
    salary: '$5,000 prize pool + Google merchandise',
    applicationDeadline: new Date('2026-08-18'),
    applyLink: 'https://gdg.community.dev/',
    contactEmail: 'gdg-india@google.com',
    status: 'Active', isFeatured: false, isDemo: true,
  },
  {
    title: 'FinTech Frontier Hackathon',
    companyName: 'HDFC Bank Innovation Lab',
    companyLogo: 'https://logo.clearbit.com/hdfcbank.com',
    category: 'Hackathons', type: 'hackathon',
    description: 'Build next-gen financial solutions for India\'s 500M unbanked and underbanked population. Problem tracks: Digital Lending, UPI Innovation, Wealth Management for Tier-2 Cities, and Fraud Prevention using AI. Finalists get internship offers and mentorship from HDFC executives.',
    requiredSkills: ['FinTech APIs', 'React/Flutter', 'Machine Learning', 'Python', 'UX Design'],
    eligibility: 'Teams of 3–5 students from any discipline. At least one technical member required.',
    location: 'Mumbai', workMode: 'Hybrid',
    salary: '₹5,00,000 prize pool across tracks',
    applicationDeadline: new Date('2026-09-05'),
    applyLink: 'https://www.hdfcbank.com/content/bbp/repositories/723fb80a-2dde-42a3-9793-7ae1be57c87f/?folderPath=/Innovation%20Lab/&fileName=Hackathon.pdf',
    contactEmail: 'innovation@hdfcbank.com',
    status: 'Active', isFeatured: false, isDemo: true,
  },

  // ─── SCHOLARSHIPS (3) ────────────────────────────────────────────────────
  {
    title: 'National Scholarship for Engineering Excellence',
    companyName: 'Tata Trusts',
    companyLogo: 'https://logo.clearbit.com/tatatrusts.org',
    category: 'Scholarships', type: 'scholarship',
    description: 'Tata Trusts\' flagship scholarship programme supports 500 meritorious engineering students from economically weaker sections annually. The scholarship covers full tuition fees, hostel, and a monthly stipend for the entire degree duration. Awardees also receive mentorship from Tata Group executives.',
    requiredSkills: ['Academic Excellence', 'Leadership', 'Community Service'],
    eligibility: 'First-year B.Tech students from EWS/OBC. Family income ≤ ₹6 lakhs/year. CGPA ≥ 8.0.',
    location: 'Pan India', workMode: 'Remote',
    salary: '₹2,50,000/year (full duration)', salaryMin: 250000, salaryMax: 250000,
    applicationDeadline: new Date('2026-09-30'),
    applyLink: 'https://www.tatatrusts.org/our-work/individual-grants-programme/education',
    contactEmail: 'scholarships@tatatrusts.org',
    status: 'Active', isFeatured: true, isDemo: true,
  },
  {
    title: 'Aditya Birla Scholarships 2026',
    companyName: 'Aditya Birla Group',
    companyLogo: 'https://logo.clearbit.com/adityabirlacapital.com',
    category: 'Scholarships', type: 'scholarship',
    description: 'Awarded to the top-ranked student from each partner IIT, IIM, BITS Pilani, XLRI, NID, NLU, and NIFT campus. The scholarship includes ₹65,000 cash, a citation, and networking access with Aditya Birla Group CEOs and leaders. One of India\'s most prestigious student awards.',
    requiredSkills: ['Academic Excellence', 'Leadership', 'Extracurricular Achievements'],
    eligibility: 'Rank 1 student from participating campuses in the current academic year.',
    location: 'Pan India', workMode: 'Remote',
    salary: '₹65,000 one-time award', salaryMin: 65000, salaryMax: 65000,
    applicationDeadline: new Date('2026-10-15'),
    applyLink: 'https://adityabirlascholars.net/',
    contactEmail: 'abscholarships@adityabirla.com',
    status: 'Active', isFeatured: false, isDemo: true,
  },
  {
    title: 'INSPIRE Scholarship for Higher Education (SHE)',
    companyName: 'Department of Science & Technology, Govt. of India',
    companyLogo: 'https://logo.clearbit.com/dst.gov.in',
    category: 'Scholarships', type: 'scholarship',
    description: 'The INSPIRE SHE programme by DST awards 10,000 scholarships annually to students ranked in the top 1% of Class 12 board exams who pursue natural/basic science degrees. The scheme provides ₹80,000/year for 5 years along with a summer research mentorship at India\'s top research institutions.',
    requiredSkills: ['Science / Mathematics Aptitude', 'Research Interest'],
    eligibility: 'Pursuing B.Sc/BS/Int. M.Sc in natural sciences. Must be in top 1% of Class 12 board.',
    location: 'Pan India', workMode: 'Remote',
    salary: '₹80,000/year for 5 years', salaryMin: 80000, salaryMax: 80000,
    applicationDeadline: new Date('2026-10-30'),
    applyLink: 'https://online-inspire.gov.in/',
    contactEmail: 'inspire-she@nic.in',
    status: 'Active', isFeatured: false, isDemo: true,
  },
];

const generateDemoOpportunities = async () => {
  const Opportunity = require('../models/Opportunity');
  const existing = await Opportunity.countDocuments({ isDemo: true });
  if (existing > 0) {
    return { alreadyGenerated: true, count: existing };
  }
  const result = await Opportunity.insertMany(
    demoOpportunities.map((opp) => ({
      ...opp,
      locationType: (opp.workMode || 'Remote').toLowerCase(),
      skills: opp.requiredSkills,
    }))
  );
  return { alreadyGenerated: false, count: result.length };
};

module.exports = { generateDemoOpportunities };